### ISSUE TITLE
[PE-D][Tester C] Error exporting nameless json

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T14-1/tp#248]
![Screenshot 2023-11-03 at 11.52.15 PM.png](https://raw.githubusercontent.com/jylow/ped/main/files/d8a60af1-dbf4-457d-ac0d-86df89d8b21a.png)

Currently, I can use the CLI to export the file with no name and .json. This results in a success message. However, this file is not found anywhere and is assumed to be not created when in fact a success message is shown

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: jylow/ped#7

**Comment by aexolate** [comment]
The file is indeed created, but will be treated as a 'hidden file' in most operating systems. e.g. `.gitignore` file
